### PR TITLE
Extract URL composition to distinct methods

### PR DESCRIPTION
**Pull request by miketheman**
Attempt at extracting the URL composition from the main build method to individual methods.

I'm not certain this is the best way to do it, but as I've been working on parameterized builds, I thought I'd take the working code (which continues to grow with complexity), and see where simplification could occur.

This would be a stepping stone towards that, where the next step is to have the `job_build_url` take in more parameters and make a decision on what build URL to return based on inputs.
I had them working inline, but it started to look a little confusing, so I stepped back and tried this first.

### CODE REVIEW

**Comment by miketheman** [comment]
Hi @daniely, Brief ping on this pull. I'll merge in a couple of days if you're not around.

**Comment by daniely** [comment]
Sorry @miketheman for the delay. 

The only thing that looks weird to me is that there's a `job_url` and `jurl`. The ambiguity there is a sign that the names aren't right. Any thoughts?

**Comment by miketheman** [comment]
@daniely I was trying to figure out how to not name a variable the same name as the method, i.e.
`job_url = job_url(job['name'])` seems worse to me.

I could rename the method to something akin to `compose_job_url()` - if that would make more sense, which would result to:

    job_url = compose_job_url(job['name'])


If that's better, then I'd also suggest renaming the other methods that compose & strings to be `compose_<method>` as well.

**Comment by daniely** [comment]
What if we just change `jurl` to `named_job_url`? Is that basically what it is?

**Comment by miketheman** [comment]
That'd do it too. :) I'll change that tonight, anyhting else?

**Comment by daniely** [comment]
Nope, that's it!

**Comment by miketheman** [comment]
Merging after updated variable names.

**Pull request merged**
